### ISSUE TITLE
support arabic messages

### ISSUE THREAD

**Issue by ahegazy** [Andreasgejlm/Messenger-Conversation-Analyzer#2]
Hello again, 
so i tried your script with a conversation with Arabic words and it appeared as boxes in the conversation_analysis pdf, i would love to debug this and work on it, but i have finals tomorrow and i have already wasted alot of time :D, so i'll keep it here till i finish or for anyone to fix it.

**Comment by Andreasgejlm** [comment]
Great idea, thanks. You could probably pull the ftfy library and add support for arabic there too.

**Comment by Andreasgejlm** [comment]
Just as a heads up, it's the WordCloud package that's causing the issue. The font they are using doesn't support Arabic or Hebrew. The issue could be resolved by passing a font which supports the characters:
`wordcloud = WordCloud(font_path='/font/to/some_font').generate(text)`.
Good luck on the exam.

**Comment by ahegazy** [comment]
yup, works like a charm, keep up !

**Comment by ahegazy** [comment]
I have created a branch with arabic support for anyone facing this issue, you can find it here: [https://github.com/ahegazy/Messenger-Conversation-Analyzer/tree/supportArabic](https://github.com/ahegazy/Messenger-Conversation-Analyzer/tree/supportArabic) ,
font used: Amiri from [google fonts](https://fonts.google.com/specimen/Amiri)
